### ISSUE TITLE
Datatable filtering

### ISSUE THREAD

**Issue by mattbdean** [mattbdean/Helium#11]
There needs to be a convenient way to filter out data from the datatable.

 - [x] **Sever side**: Modify `GET /api/v1/schemas/:schema/:table/data` to support filtering via query
 - [x] **Client side**: Implement a simple UI element to provide access to these controls in `DatatableComponent`
  
Filters:

 - [x] Equal to: numbers, dates/datetimes, strings (case insensitive)
 - [x] Less than: numbers, dates/datetimes
 - [x] Greater than: numbers, dates/datetimes
 - [x] Is: `null` (any)
 - [x] Is not: `null` (any)

Additional features for the FilterComponent:

 - [x] Dropdown when an enum is selected to filter by
 - [x] Date picker
 - [x] Datetime picker

**Comment by boazmohar** [comment]
Maybe google sheets style where each column has a filter option.

**Comment by mattbdean** [comment]
I'm starting work on this issue on [this branch](https://github.com/mattbdean/Helium/tree/datatable-filtering). Right now it's just API-level stuff. What filters would we want to include? Currently it's just less than, greater than, and equal to for numbers. I was thinking about an "includes" for strings as well.

**Comment by boazmohar** [comment]
That’s great.

I think that is a good start for strings and numbers. Maybe after, before and on for dates?
I also think this is a good question for DataJoint people. Ask them how they implement this, see if we can learn anything.

**Comment by ixcat** [comment]
Hello -
Since we already do attribute filtering within DataJoint fetch() calls it might make sense to just use URL parameters and pass these through to DJ after some input sanitation - or alternately/more generally have a separate '/query' endpoint which allows some sort of stringified datajoint querying. Another thing to keep in mind is that multiple schemas are often used together in a project (although that might be less relevant to a table specific view which it seems like is being talked about here)

**Comment by mattbdean** [comment]
Helium doesn't actually use any DJ APIs, but rather works with the schemas it creates.
